# Generated by Django 4.0 on 2024-01-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapi', '0002_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='book_covers/'),
        ),
    ]
